language: php
cache:
  directories:
  - vendor
php:
  - 5.6
  - 7.0

matrix:
  fast_finish: true
    
before_install:
  - /home/travis/.phpenv/versions/$(phpenv version-name)/bin/composer self-update
    
before_script:
  - composer require --dev satooshi/php-coveralls:dev-master
  - composer install
  
after_script:
  - export COVERALLS_RUN_LOCALLY=1
  - php bin/coveralls -v

script: 
  - vendor/bin/phpunit --coverage-text
