language: php

php:
  - 7.0

before_install:
 - /home/travis/.phpenv/versions/$(phpenv version-name)/bin/composer self-update
 - if [[ $TRAVIS_PHP_VERSION =~ (^7|^nightly) ]]; then wget https://github.com/nicolasff/phpredis/archive/php7.zip && unzip php7.zip && cd phpredis-php7 && phpize && ./configure && make && make install; fi 
  
before_script:
  - composer install

script: 
  - vendor/bin/phpunit --coverage-text

services:
  - redis-server
