language: php

php:
  - 5.6
  - 7.0

before_install:
  - /home/travis/.phpenv/versions/$(phpenv version-name)/bin/composer self-update
    
before_script:
  - composer install

script: 
  - vendor/bin/phpunit --coverage-text
